version: 2

project_name: contextgate

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: contextgate
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: orimyth
      name: homebrew-contextgate
    homepage: https://github.com/orimyth/contextgate
    description: Security & observability layer for AI agents
    license: MIT
    install: |
      bin.install "contextgate"
    test: |
      system "#{bin}/contextgate", "version"
